"""rename department

Revision ID: 58609b98ccb4
Revises: cd4fd5b1641d
Create Date: 2024-04-04 18:33:34.378422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58609b98ccb4'
down_revision = 'cd4fd5b1641d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
